### ISSUE TITLE
about the weight norm

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [happynear/AMSoftmax#1]
hi @happynear,
i read the code of `innerproduct`, find that, you only norm the `weights` in the `forward` pass. so why it does not need corresponding `bp`?

thanks.

**Comment by happynear** [comment]
Because we directly change the weights in the forward propagation. We find the performance is similar with calculating the gradients of the normalization, and it looks much clearer. 

You may also try a more correct way as in https://github.com/happynear/NormFace/blob/master/prototxt/combine_softmax_contrastive.prototxt .

**Comment by zimenglan-sysu-512** [comment]
thanks.
